ui: mocha-tdd
browsers:
  - name: internet explorer
    version: 6..latest
  - name: chrome
    version: [26, latest]
  - name: firefox
    version: ['3.0', latest]
  - name: safari
    version: [5, latest]
  - name: opera
    version: [11, latest]
  - name: ipad
    version: ['4.3', latest]
  - name: iphone
    version: ['4.3', latest]
  - name: android
    version: ['4.0',latest]
